version: '3.8'

services:
  mailer:
    container_name: mailer
    hostname: mailer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./data:/mailer/data
    ports:
      - "8080:8080"
